### ISSUE TITLE
How is this executed?

### ISSUE THREAD

**Issue by lillythomas** [shekkizh/FCN.tensorflow#15]
Hi there!

This set up looks very useful for me! I am trying to run this on my own set of images and labels.  I don't see any instructions on how to execute the app though.  Could you perhaps shed some light on this?

Thanks in advance!
Lilly

**Comment by shekkizh** [comment]
Have updated Readme to answer this. 
For training on different dataset you will need to modify the read_MITSceneParsingData.py and BatchDatasetReader.py

Cheers.
