### ISSUE TITLE
Can I train the net with images without resizing?

### ISSUE THREAD

**Issue by abc8350712** [shekkizh/FCN.tensorflow#18]
Can I use images with different size to train the FCN?

**Comment by shekkizh** [comment]
AFAIK tensorflow still doesn't support variable image size batches. 
Some of the hacks you can do to solve the problem is zero pad all images to a constant size or take constant sized patches of the input image and train.

**Comment by hanyangii** [comment]
In this code, if I change resize value of image options to 'True', can it be trained without resizing?

**Comment by shekkizh** [comment]
@hanyangii To train images without resizing set resize to False. Note that tensorflow doesn't support variable image size batches. So the code works only if the images are of same size.
