### ISSUE TITLE
Line 152 in FCN.py

### ISSUE THREAD

**Issue by Hydraz320** [shekkizh/FCN.tensorflow#2]
Sorry to bother you Mr.Shekkizh,  I just have a problem when I run this code and get following 

> Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/framework/tensor_shape.py", line 547, in merge_with
    self.assert_same_rank(other)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/framework/tensor_shape.py", line 593, in assert_same_rank
    "Shapes %s and %s must have the same rank" % (self, other))
ValueError: Shapes (?, ?, ?, 151) and (?, ?) must have the same rank

And I find out that this exception comes from here
`
loss = tf.reduce_mean((tf.nn.sparse_softmax_cross_entropy_with_logits(logits,
                                                                          tf.squeeze(annotation, squeeze_dims=[3]),
                                                                          name="entropy")))
`

I test on the shape of logits and  tf.squeeze(annotation, squeeze_dims=[3]),  they are (?, ?, ?, 151) and (?, 224, 224) seperately.
So is there anything wrong?  I'm a little confused and hoping for your advice. Thanks a lot.

**Comment by shekkizh** [comment]
Hi @Hydraz320,
I wrote this code in python 2.7 and tensorflow v0.10. If nothing else was changed, I think the error might have to do with api changes. I will take a look into the problem later and will update here if anything comes up.

**Comment by Hydraz320** [comment]
Thank you for your reply！I run the code in python 3.5 and tf0.11 and I did ignore the version problem. I'll have a check about that.


thx :D


发自网易邮箱大师
On 12/14/2016 21:28, Sarath Shekkizhar wrote:

Hi @Hydraz320,
I wrote this code in python 2.7 and tensorflow v0.10. If nothing else was changed, I think the error might have to do with api changes. I will take a look into the problem later and will update here if anything comes up.

**Comment by HosnaCSE** [comment]
Hello  @Hydraz320,

Do you able to solve the problem? I also encounter the same problem. I have python 3.5 and tf0.12.

**Comment by mustafaIhssan** [comment]
Just change it to `loss = tf.reduce_mean((tf.nn.sparse_softmax_cross_entropy_with_logits(logits=logits,
                                                                      labels=tf.squeeze(annotation, squeeze_dims=[3]),
                                                                      name="entropy")))`
and it will work

**Comment by jiao0805** [comment]
I got the same problem too, have you saved it?

**Comment by jiao0805** [comment]
I fixed my problem and I found that the cross entropy function actually needs four parameters.
Please have a look on this:
def _ensure_xent_args(name, sentinel, labels, logits):
#Make sure that all arguments were passed as named arguments.
if sentinel is not None:
raise ValueError("Only call %s with "
"named arguments (labels=..., logits=..., ...)" % name)
I found them in the declaration of tf.nn.sparse_softmax_cross_entropy_with_logits()
I tried this:

None,
tf.squeeze(annotation, squeeze_dims=[3]),
logits,
"entropy")))

or:
logits=logits,
labels=tf.squeeze(annotation, squeeze_dims=[3]),
 name="entropy")))

**Comment by Edwardmark** [comment]
you should call the function by writing : 
loss = tf.reduce_mean((tf.nn.sparse_softmax_cross_entropy_with_logits(logits = logits,
                                                                          labels = tf.squeeze(annotation, squeeze_dims=[3]),
                                                                          name="entropy")))
it's actually the error with the version difference
