### ISSUE TITLE
Line 47 BatchDatsetReader.py

### ISSUE THREAD

**Issue by cbessega** [shekkizh/FCN.tensorflow#21]
Hi @shekkizh 
First, thank you for sharing the code with us. 
I have a question, the if statement on line 47 on BatchDatsetReader says:

```python
if self.image_options.get("resize", False) and self.image_options["resize"]:
    resize_size = int(self.image_options["resize_size"])
    resize_image = misc.imresize(image,
                                  [resize_size, resize_size], interp='nearest')
else:
     resize_image = image
```
I think is should be:

```python
if self.image_options.get("resize", True) and self.image_options["resize_size"]:
    resize_size = int(self.image_options["resize_size"])
    resize_image = misc.imresize(image,
                                [resize_size, resize_size], interp='nearest')
else:
    resize_image = image
```

Am I misinterpreting the parameters?

Thanks!

**Comment by shekkizh** [comment]
The intention of the if statement was to check if the dictionary has "resize" and if it's value is set to True. Now that I look at the code the second condition `self.image_options["resize"]` seems redundant as the get returns the value if the dictionary contains the key.
Thanks for pointing out, I will clean up the code.

Fyi, the version you posted has default True in get which is incorrect as this would mean that a dictionary without resize key is considered as resize set to True.

**Comment by cbessega** [comment]
Thank you @shekkizh
