### ISSUE TITLE
Prediction output of size 224x224 as opposed to original dimensions

### ISSUE THREAD

**Issue by lillythomas** [shekkizh/FCN.tensorflow#23]
Hey again!

Sorry for opening another issue, but I am in the home stretch of getting this codebase suited to my data and almost everything is coming together.  

So the output predictions are of size 224x224x1 and for my purposes I need to reconstruct the images back together with their geo-location intact.  In order to do so however, I need the output predictions to be of size 256x256x1.  

Do you know if there is a way to restore the predictions to those dimensions without changing the segmentation mapping or resolution?

Thank you again for both this awesome repo and for your help!!

**Comment by lillythomas** [comment]
Never mind, I figured it out!  Sorry for the confusion, I will close this ticket.

**Comment by SoulGuedria** [comment]
Hi @lillythomas 

Can you tell me how you solved the problem? Thank you :)
