### ISSUE TITLE
The code in FCN.py,line 86, the final conv layer should be conv5_4 not conv5_3

### ISSUE THREAD

**Issue by Edwardmark** [shekkizh/FCN.tensorflow#25]
Hi there,
I notice that in FCN.py,line 86, it says:
conv_final_layer = image_net["conv5_3"]
but actually according to the model you're using ,the conv_final_layer should be conv5_4.
Is that right? Or could you please tell me why you use conv5_3 instead?
Thanks

**Comment by 906476903** [comment]
https://github.com/shekkizh/FCN.tensorflow/issues/7

**Comment by shichaosuper** [comment]
I think this question has been answered...
https://github.com/shekkizh/FCN.tensorflow/issues/7
