### ISSUE TITLE
 [[Node: entropy/entropy = SparseSoftmaxCrossEntropyWithLogits[T=DT_FLOAT, Tlabels=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](entropy/Reshape, entropy/Reshape_1)]]

### ISSUE THREAD

**Issue by Yaredoh** [shekkizh/FCN.tensorflow#28]
----- 7 198 197 196 196 197 196 196 201 197 197 198 190 166 133 130 131 131 132 132 132 132 132 133 133 133 134 129 114 104 96 69 17 10 10 28 124 133 132 132 132 132 132 131 131 131 131 131 130 131 133 132 132 132 133 133 132 132 132 132 132 132 132 132 132 132 132 133 134 133 133 133 133 133 133 133 133 133 133 127
	 [[Node: entropy/entropy = SparseSoftmaxCrossEntropyWithLogits[T=DT_FLOAT, Tlabels=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](entropy/Reshape, entropy/Reshape_1)]]

This error stoped the traing. Is this related to softmax ?
loss = tf.reduce_mean((tf.nn.sparse_softmax_cross_entropy_with_logits(logits=logits,
                                                                          labels=tf.squeeze(annotation, squeeze_dims=[3]),
                                                                          name="entropy")))

**Comment by shekkizh** [comment]
The error is unclear. Can you add more detail to the issue? 
It seems you were able to train and the error occurred after some time?! Possible error with the annotation file?

**Comment by Yaredoh** [comment]
```setting up vgg initialized conv layers ...
Setting up summary op...
Setting up image reader...
Found pickle file!
50
15
Setting up dataset reader
Initializing Batch Dataset Reader...
{'resize_size': 224, 'resize': True}
(50, 224, 224, 3)
(50, 224, 224, 1)
Initializing Batch Dataset Reader...
{'resize_size': 224, 'resize': True}
(15, 224, 224, 3)
(15, 224, 224, 1)
Setting up Saver...
Traceback (most recent call last):

  File "<ipython-input-1-12b2e3f5c7e5>", line 1, in <module>
    runfile('C:/Users/Yared/Desktop/Project/FCN.py', wdir='C:/Users/Yared/Desktop/Project')

  File "C:\Users\Yared\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "C:\Users\Yared\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Yared/Desktop/Project/FCN.py", line 227, in <module>
    tf.app.run()

  File "C:\Users\Yared\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))

  File "C:/Users/Yared/Desktop/Project/FCN.py", line 198, in main
    sess.run(train_op, feed_dict=feed_dict)

  File "C:\Users\Yared\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 767, in run
    run_metadata_ptr)

  File "C:\Users\Yared\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 965, in _run
    feed_dict_string, options, run_metadata)

  File "C:\Users\Yared\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1015, in _do_run
    target_list, options, run_metadata)

  File "C:\Users\Yared\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)



InvalidArgumentError: Received a label value of 250 which is outside the valid range of [0, 151).  Label values: 66 57 54 59 60 59 54 65 111 133 133 144 150 154 160 166 165 159 155 135 44 25 15 13 13 12 13 13 14 16 16 30 50 61 70 72 71 77 87 102 110 112 102......................42 76 103 105 110 108 62 28
	 [[Node: entropy/entropy = SparseSoftmaxCrossEntropyWithLogits[T=DT_FLOAT, Tlabels=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](entropy/Reshape, entropy/Reshape_1)]]
```

Thanks for your help.

**Comment by shekkizh** [comment]
The error is pretty clear - your annotation file has value 250 when the NUM_OF_CLASSES range from [0, 151). If this is your custom dataset try processing your annotation file to have values within range.

**Comment by Yaredoh** [comment]
Thanks, for your help. What do you mean try processing your annotation file to have values within the range?  How can I do that? I was trying to assign default label if it is out of range. How can I control it the label to not be out of the range? Thanks for your help.

**Comment by Yaredoh** [comment]
Thanks. I know the error. initially i trained the network with 151 number of classes and when i try to change the number of classes to 250 and train it again gave me the error. it was holds the initial number of classes value. I cloned the script again as a new and works with 250 number of class perfectly.

**Comment by matvaibhav** [comment]
@Yaredoh @shekkizh  Sorry to bother you but could you please tell me if my number of classes is 2, what all changes need to be done? While training I set NUM_OF_CLASSES as 3. Which one is the annotation file? What changes have to be made in it? Sorry if the question is stupid but I am new to tensorflow. Thanks in advance.

**Comment by xcnie** [comment]
> @Yaredoh @shekkizh Sorry to bother you but could you please tell me if my number of classes is 2, what all changes need to be done? While training I set NUM_OF_CLASSES as 3. Which one is the annotation file? What changes have to be made in it? Sorry if the question is stupid but I am new to tensorflow. Thanks in advance.

hello，I meet the same question,  do you solve it?

**Comment by BaoanhTrinh** [comment]
@matvaibhav @xcnie and anyone else: if you have a grayscale image, NUM_OF_CLASSES should be 256. It means your image has pixels' value from 0 to 255
