### ISSUE TITLE
Question: FCN32, FCN16, or FCN8?

### ISSUE THREAD

**Issue by lillythomas** [shekkizh/FCN.tensorflow#29]
I just wanted to know if this is an implementation of an FCN 32, 16, or 8...Thanks in advance.

**Comment by shekkizh** [comment]
Running the implementation as such would be FCN-8. Though the other FCN models can be obtained by slightly modifying code.

**Comment by dlrPHS2** [comment]
I'm new to Deep Learning. Can you give me a hint how I have to do the upscoring on 32s or 16s?
Many Thanks in Advance!
