### ISSUE TITLE
bottleneck_unit() - TensorflowUtils.py - line 159

### ISSUE THREAD

**Issue by dubvulture** [shekkizh/FCN.tensorflow#30]
Hi, I was wondering what was the aforementioned [function](https://github.com/shekkizh/FCN.tensorflow/blob/master/TensorflowUtils.py#L159).
It is used nowhere in the code and I cannot find anything similar described in the [paper](https://arxiv.org/pdf/1605.06211.pdf).

Thanks in advance.

**Comment by shekkizh** [comment]
TensorflowUtils contains functions that I generally use while working on projects. As such with respect to this particular project it might have unused functions. Sorry for any confusion.
