### ISSUE TITLE
How to calculate the segmentation accuracy of the model？

### ISSUE THREAD

**Issue by yeshenlin** [shekkizh/FCN.tensorflow#33]
hello，thanks for your code!
I have finished training the model, how to calculate the segmentation accuracy of the model？

**Comment by obendidi** [comment]
Hello , I used this repo for that https://github.com/martinkersner/py_img_seg_eval
with input the gt_img and the predicted image

**Comment by yeshenlin** [comment]
@bendidi Thanks for your help!   ^_^
