### ISSUE TITLE
Test with single image 

### ISSUE THREAD

**Issue by Yaredoh** [shekkizh/FCN.tensorflow#34]
How can we test it with single image with out giving it training label/mask ? To predict the segmentation ?

**Comment by Yaredoh** [comment]
**I was trying to predict the given untrained / unknown image segmentation just like this. But it gave me dimension error. The error is " ValueError: could not broadcast input array from shape (2,224,224,3) into shape (2,224,224) ". How to predict with trained model on a different dataset? I stacked on this.**

    elif FLAGS.mode == "predict":
                     
        predict_dataset_reader = dataset.BatchDatset(predict_records, image_options)
        predict_images = predict_dataset_reader.get_random_batch(FLAGS.batch_size)
        pred = sess.run(pred_annotation, feed_dict={image: predict_images, 
                                                    keep_probability: 1.0})
        pred_annotations = np.squeeze(pred_annotations, axis=3)
        pred = np.squeeze(pred, axis=1)

        for itr in range(FLAGS.batch_size):
            utils.save_image(predict_images[itr].astype(np.uint8), FLAGS.logs_dir, name="inp_" + str(20+itr))
            utils.save_image(pred[itr].astype(np.uint8), FLAGS.logs_dir, name="pred_" + str(20+itr))
            print("Saved image: %d" % itr)

**Comment by shekkizh** [comment]
The error is because of your image file being grayscale. 

Closing as this is more of a user error.
