### ISSUE TITLE
A possible bug when resizing annotations.

### ISSUE THREAD

**Issue by gjy3035** [shekkizh/FCN.tensorflow#4]
If resize==true, the image and annotation will be resized to a given size.
However, in the resizing process of the annotation, the interpolation method is default: bilinear,  which causes some mistakes labels near the edge of objects.  
So, I think the interpolation method should be 'nearest' when resizing annotations.

Thanks a lot!

**Comment by shekkizh** [comment]
Yes. This would be a bug. It's effect is less pronounced since we train with loss objective calculated on whole image and in mini batches. Have updated the code for resize with "nearest" for both image and annotation.

Thanks for pointing out the bug.
