### ISSUE TITLE
How to visualize the prediction?

### ISSUE THREAD

**Issue by Dean-TianZhang** [shekkizh/FCN.tensorflow#40]
I have run the command "python FCN.py --mode=visualize", but I got result far different from the author's result. Here is my result:

![image](https://cloud.githubusercontent.com/assets/18567646/26775233/8e1a3958-4a06-11e7-9b21-44be2552b717.png)

Does anyone know what should I do, and how to apply the whole model in my own dataset and test data set?

Thanks.

**Comment by xiaoxionglin** [comment]
You have to train it first. The code does not contain the trained model.

**Comment by Nii-co** [comment]
Hi Dean, got the same issue here, and I see the code downloaded a model from http://www.vlfeat.org/matconvnet/models/beta16/imagenet-vgg-verydeep-19.mat, I thought it was the trained model for this project, but looks like it's not? So we need to trained from the beginning first?

**Comment by xiaoxionglin** [comment]
That's the model for object recognition. This program trains on the basis of that.

**Comment by Nii-co** [comment]
Thanks for explanation, but why do we need an object recognition model? As I know FCN itself can do the recognition work independently, or maybe this extra model is for a better performance? 
By the way, if my requirement is just to find a bottle in the image, and suppose this object recognition model can't recognize bottles, do I need to retrain the object recognition model first?

**Comment by ChinmayKalyankar** [comment]
@lxx74n74n  can you help me how to train a model using this code...?
I mean what all things I have to download before doing it and which commands to fire ??
