### ISSUE TITLE
how to decrease space used for logging?

### ISSUE THREAD

**Issue by bhralz** [shekkizh/FCN.tensorflow#41]
Dear all,
I have some limitations on hard disk space on shared server,
Is there any necessity for logging? Or  how I can use some smaller space for logging?
How I can decrease the size need  for logging?
Please guide step by step
Any comment appreciated.
Thanks

**Comment by xiaoxionglin** [comment]
you can set parameters of tensorflow how many checkpoints you want to keep. By default it's 5. And one checkpoint is around 2 GB.

**Comment by bhralz** [comment]
Is it possible to give an example in relation to this case?

**Comment by xiaoxionglin** [comment]
I am not an expert. Just encountered the similar problem when implementing this code.
there is sth in folder "logs" called:
model.ckpt-500.data-00000-of-00001
as such.
it should be the main model data.
by default it saves every 500 iterations, you can change it in the file "FCN.py" near the end. sth like:
if iter%500==0

The thing I mentioned in the last post:
https://www.tensorflow.org/versions/r0.11/api_docs/python/state_ops/saving_and_restoring_variables

you can modify the parameter "Max_to_keep" to a lower value, maybe 1 or 2

**Comment by bhralz** [comment]
Ok thanks
