### ISSUE TITLE
Test the trained model?

### ISSUE THREAD

**Issue by bhralz** [shekkizh/FCN.tensorflow#43]
Dear all,
How I can test the trained model on a group of new images?
thanks for your help.

**Comment by bhralz** [comment]
Isnt there any reply?

**Comment by Nii-co** [comment]
Hi, did you find a solution to this question? @bhralzz

**Comment by WANGYuSCU** [comment]
I have the same question and I find that in the beginning, annotation/validation is there. But I think it should be there after the training and validation process. Maybe I am wrong about this. Could anyone tell me about that?

**Comment by sldyb** [comment]
Hello
I want test a new image with the trained model too.
Are you achieved?
Please

**Comment by bhralz** [comment]
Yes
Its a simple step.
