### ISSUE TITLE
relu5_3

### ISSUE THREAD

**Issue by yossitsadok** [shekkizh/FCN.tensorflow#46]
Hello,

Is there a particular reason why the Inference continue from the "conv5_3" level of the vgg_net and not from the "relu5_3" ?  I mean teh input to "POOL 5" is "conv5_3" and not "relu5_3"

What am i missing?

Thanks!

**Comment by shekkizh** [comment]
My take is that relu layers by themselves aren't going to affect the inference in this case since they are merely thresholding functions. Not sure if that answers your question but am closing this issue for now.

**Comment by varungupta31** [comment]
@yossitsadok https://github.com/shekkizh/FCN.tensorflow/issues/94#issuecomment-1108473347
