### ISSUE TITLE
The order of the fc layers

### ISSUE THREAD

**Issue by Edwardmark** [shekkizh/FCN.tensorflow#47]
Do you know how to load the fully-connected layers as you load the conv layers
is the following still true for fully-connected layers?
# matconvnet: weights are [width, height, in_channels, out_channels]
# tensorflow: weights are [height, width, in_channels, out_channels] 
the output of pool5 with a image with shape[1,224,224,3] is [1,7,7,512], and the fc6 weight is [7,7,512,4096], so how to flatten the weight in matconvnet to fit the format of tensorflow?

**Comment by shekkizh** [comment]
fully connected layers should have shape [input_size, output_size]. I don't think you need to perform any changes to convert to tf format.

In your example I think the fc6 weights will be of shape [7x 7x512, 4096].

**Comment by Edwardmark** [comment]
@shekkizh I know what you mean,but should we first change the order of the first two dimension of fc6 weight and then flatten that?
