### ISSUE TITLE
Why the scale factor in caffemodel is ignored in tf equivalent? Should we scale the input to 1/256 or 1/128 as caffe used to do?

### ISSUE THREAD

**Issue by Edwardmark** [shekkizh/FCN.tensorflow#48]
Why the scale factor in caffemodel is ignored in tf equivalent? Should we scale the input to 1/256 or 1/128 as caffe used to do?

**Comment by Edwardmark** [comment]
Why not scale the image to have maximum of 1?

**Comment by shekkizh** [comment]
The pre-trained vgg model afaik used only mean subtracted images without scaling. Since we initialize with trained values I think it's fair to not scale the images.

Can you point to where you found scaling using in models trained in caffe?
