### ISSUE TITLE
ValueError: Cannot feed value of shape (0,) for Tensor 'input_image:0', which has shape '(?, 224, 224, 3)'

### ISSUE THREAD

**Issue by jabgle** [shekkizh/FCN.tensorflow#51]
why i can't run this programs？？

**Comment by Keep-Passion** [comment]
I meet this problem too, is there some resolution?

**Comment by TheRevanchist** [comment]
Most certainly, the pickle file is getting created in a wrong way (which means that it isn't finding any file there) and then TF tries to feed an empty tensor of size (0,) as input which results in an error.

Are you perhaps using some other dataset?

**Comment by Keep-Passion** [comment]
My project is tensorflow 1.1.0 + python3.5 in windows 7 
I just used the MIT_SeceneParsing dataSet, I use the code to download and extract automatically. The print result is as follows:
setting up vgg initialized conv layers ...
Setting up summary op...
Setting up image reader...
./Data_zoo/MIT_SceneParsing/MITSceneParsing.pickle
Found pickle file!
0
0
Setting up dataset reader
Initializing Batch Dataset Reader...
{'resize_size': 224, 'resize': True}
(0,)
(0,)
Initializing Batch Dataset Reader...
{'resize_size': 224, 'resize': True}
(0,)
(0,)
@TheRevanchist

**Comment by TheRevanchist** [comment]
Try to delete all the logs and the pickle file and redo everything. I had the same problem when I changed the dataset, and by doing that it was fixed.

In addition, look if the images are in the right format. The code that builds the pickle file looks for jpg images (around line 46 or so). If the images are in png or some other format, it won't find anything and will build an empty pickle file which will later result on your error.

@MATony

**Comment by muradalqurishee** [comment]
Help me please

% (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))

ValueError: Cannot feed value of shape (224, 224) for Tensor 'conv2d_2_input:0', which has shape '(?, 224, 224, 3)'

**Comment by theparitt** [comment]
I am not sure but it seems the problem is pickle file in \Data_zoo\MIT_SceneParsing\MITSceneParsing.pickle I contain  Chinese Characters

**Comment by doublemanyu** [comment]
> 
> 
> My project is tensorflow 1.1.0 + python3.5 in windows 7
> I just used the MIT_SeceneParsing dataSet, I use the code to download and extract automatically. The print result is as follows:
> setting up vgg initialized conv layers ...
> Setting up summary op...
> Setting up image reader...
> ./Data_zoo/MIT_SceneParsing/MITSceneParsing.pickle
> Found pickle file!
> 0
> 0
> Setting up dataset reader
> Initializing Batch Dataset Reader...
> {'resize_size': 224, 'resize': True}
> (0,)
> (0,)
> Initializing Batch Dataset Reader...
> {'resize_size': 224, 'resize': True}
> (0,)
> (0,)
> @TheRevanchist

Have you solve it? How to solve?

**Comment by kunyu17** [comment]
> Try to delete all the logs and the pickle file and redo everything. I had the same problem when I changed the dataset, and by doing that it was fixed.
> 
> In addition, look if the images are in the right format. The code that builds the pickle file looks for jpg images (around line 46 or so). If the images are in png or some other format, it won't find anything and will build an empty pickle file which will later result on your error.
> 
> @matony

do you know how to deal with it? i have tried your method but it doesnot function

**Comment by DeepWu** [comment]
i have solve this problem.
1.修改代码为      filename = os.path.splitext(f.split("\\")[-1])[0] (注意：如果写成 // 也会报上述错误)
2.删除生成的.ckpt文件（错误的运行也会生成这个文件，如果想解决问题一定要删除）
3.清空logs目录下的所有文件
4.运行FCN.py
