### ISSUE TITLE
How to test and demo?

### ISSUE THREAD

**Issue by zhangzhizz** [shekkizh/FCN.tensorflow#53]
hi,i have completed the train but i don't know how to test it?and how to demo it?can you help me ?

**Comment by Endless-Hao** [comment]
I also want to know.Do you solve it.

**Comment by cdathuraliya** [comment]
Just run `python FCN.py --mode=visualize`

**Comment by zhangzhizz** [comment]
@cdathuraliya  ok ， i had know ，thank you

**Comment by XZNWU** [comment]
I have completed the train . but I just want to test an image, and get a segmentation image, how to achieve?

**Comment by bkwwangjie** [comment]
Hello, I always make mistakes when I train the internet. Can you tell me the specific training?

**Comment by bkwwangjie** [comment]
When the code is executed to "print(setting up saver)"it is interrupted,thanks。Also, what if I want to use my own dataset?

**Comment by cdathuraliya** [comment]
@bkwwangjie Posting your console log can be more helpful for others to help you.

**Comment by cdathuraliya** [comment]
@xiangzhang06 It is not supported out of the box as far as I know. But you can make some changes (reading your own image and feeding in as `valid_images` maybe) here https://github.com/shekkizh/FCN.tensorflow/blob/master/FCN.py#L208 to achieve what you need.

**Comment by XZNWU** [comment]
thank you very much

At 2017-12-18 17:54:02, "CD Athuraliya" <notifications@github.com> wrote:


@xiangzhang06 It is not supported out of the box as far as I know. But you can make some changes (reading your own image and feeding in as valid_images maybe) here https://github.com/shekkizh/FCN.tensorflow/blob/master/FCN.py#L208 to achieve what you need.
