### ISSUE TITLE
A question in Image_Cmaped.ipynb

### ISSUE THREAD

**Issue by fanhualta** [shekkizh/FCN.tensorflow#56]
In the Image_Cmaped.ipynb, there has a plt.imshow(gt, cmap=cm.Paired ,vmin=0, vmax=151)
I don't know about cmap=cm.Paired, I know that cm is matplotlib.cm, but I cann't find the description about cm.Paired in the matplotlib.org
Can you kindly enough to tell me what it is meant?

**Comment by fanhualta** [comment]
@shekkizh sorry to bother you ,please help me if you are free,thanks

**Comment by shekkizh** [comment]
It is just the color map to use.
