### ISSUE TITLE
Question: why use "np.transpose()" to change the weights when you initialize the weights of conv layers? when I  read others code(https://github.com/MarvinTeichmann/tensorflow-fcn/blob/master/fcn8_vgg.py), I find they don't transpose the vgg16-weights. Note that the his vgg16-weights is equal with your used weights except the weights of conv1_1. So I feel confused whether it is necessary to transpose the vgg16-weights when initializing the weights of conv?

### ISSUE THREAD

**Issue by OREAw** [shekkizh/FCN.tensorflow#72]
Question: why use "np.transpose()" to change the weights when you initialize the weights of conv layers? when I  read others code(https://github.com/MarvinTeichmann/tensorflow-fcn/blob/master/fcn8_vgg.py), I find they don't transpose the vgg16-weights. Note that the his vgg16-weights is equal with your used weights except the weights of conv1_1. So I feel confused whether it is necessary to transpose the vgg16-weights when initializing the weights of conv?

**Comment by shekkizh** [comment]
Don't remember the other code. The reason for transpose is commented in code.
