### ISSUE TITLE
"MITSceneParsing.pickle" Do I need to download this file?

### ISSUE THREAD

**Issue by tanxjtu** [shekkizh/FCN.tensorflow#91]
# Is this file required for me to download? Ask what I have wrong, I am a beginner
###
  File ".../read_MITSceneParsingData.py", line 38, in read_dataset
    training_records = result['training']  
TypeError: 'NoneType' object is not subscriptable

**Comment by fourk-ty** [comment]
You only need to download the original dataset and carefully set the data_dir right.

**Comment by Mingtzge** [comment]
hey @fourk-ty @tanxjtu 
Sorry to trouble you!
I am using ubuntu16.04 to run FCN.py and I am getting the same error with tanxjtu 
I downloaded the ADEChallengeData2016.zip and i put it in the Date_zoo/MIT_SceneParsing directory.
Like this:
![image](https://user-images.githubusercontent.com/36849533/38454203-11d59600-3a95-11e8-8161-0ae384440390.png)
What's wrong whit that?and how can i fix this problems?
Looking for your reply!
Thanks a lot!

Best regards!

**Comment by Mingtzge** [comment]
I fixed my problems.
I removed the Date_zoo file and ran FCN.py to download dataset automatically. 
my project work well !
