### ISSUE TITLE
The newcomer asked the gods how to fine-tune the model. It is what kind of output back-propagation or other operations？

### ISSUE THREAD

**Issue by peppaJoeng** [shekkizh/FCN.tensorflow#92]
Excuse me, I want to implement transfer learning. However, I can't read the meanings of the variables Ratio, Train, and Val in ADEChallengeData2016/objectInfo150.txt, so I don't know how to change it. I just started learning, so I don't understand very well. Can someone tell me why I set the number of categories to 150 and how does the subsequent code use this value to backpropagate or fine-tune the model? My original understanding was that the FCN trains for each pixel. However, the 150 categories refer to different types of images, not to every pixel. And if it is a fully connected layer at the end, then use a one-dimensional vector to represent this category. This category is set to one, and the rest of the categories are set to zero. How do you express it for deconvolution at the end? So how does it distinguish between grasses, buildings, or bathrooms and use different colors for images that have never been trained before?

**Comment by roestigraben** [comment]
The 150 classes refer to the amount of types of objects in the image. If you look at the ground truth images, you ill see that the pixels may have up to 150 different values dependant of what is present in the image. So a class may be chair or people etc.

**Comment by peppaJoeng** [comment]
Thank you very much for your enthusiasm for answering.I already know what the categories mean and what categories are modified.
