### ISSUE TITLE
ValueError: Cannot feed value of shape (0,) for Tensor 'input_image:0', which has shape '(?, 224, 224, 3)'

### ISSUE THREAD

**Issue by MarkYangjiayi** [shekkizh/FCN.tensorflow#95]
Hello,
I faced this problem. It will be a matter of appreciation if anyone will help me.
Thanks

**Comment by sldyb** [comment]
Hello,
Did you solve this problem? I also encountered this problem.
Could you help me

Thanks

**Comment by MarkYangjiayi** [comment]
@sldyb Yes, I found the solution. You should definitely read the third point of issue#9:https://github.com/shekkizh/FCN.tensorflow/issues/9
It says very clearly that on windows you should use "\\" instead of "/", because the other one is for linux

**Comment by sldyb** [comment]
@MarkYangjiayi Thank you very much. I have solved the problem.

**Comment by YCYchunyan** [comment]
@sldyb  hi,
I encountered this problem too, I have read the third point of issue#9,but I still can't solve my problem.Can you tell me the solution.
thanks

**Comment by MarkYangjiayi** [comment]
I’m glad you solved it




    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            
                            
                            
                                
                                    邮箱：1923859@gmail.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制
On 04/29/2018 16:56, YCYchunyan wrote: @sldyb  hi,
I encountered this problem too, I have read the third point of issue#9,but I still can't solve my problem.Can you tell me the solution.
thanks

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/shekkizh/FCN.tensorflow","title":"shekkizh/FCN.tensorflow","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/shekkizh/FCN.tensorflow"}},"updates":{"snippets":[{"icon":"PERSON","message":"@YCYchunyan in #95: @sldyb  hi,\r\nI encountered this problem too, I have read the third point of issue#9,but I still can't solve my problem.Can you tell me the solution.\r\nthanks"}],"action":{"name":"View Issue","url":"https://github.com/shekkizh/FCN.tensorflow/issues/95#issuecomment-385236380"}}}

**Comment by sldyb** [comment]
Hi @YCYchunyan 
see here:
`SceneParsing_folder = os.path.splitext(DATA_URL.split("/")[-1])[0]
filename = os.path.splitext(f.split("\\")[-1])[0] `

**Comment by ZLC-RS** [comment]
Hi  @YCYchunyan 
see here:
`SceneParsing_folder = os.path.splitext(DATA_URL.split("/")[-1])[0]
filename = os.path.splitext(f.split("\\")[-1])[0] `

**Comment by a123935132** [comment]
@sldyb hello,I also have this problem,I have modified SceneParsing_folder = os.path.splitext(DATA_URL.split("/")[-1])[0] filename = os.path.splitext(f.split("\\")[-1])[0], but I still can't do that,Can you help me again,thank you very much.

**Comment by MarkYangjiayi** [comment]
@a123935132 I think you should check if you changed the code at the right place, because there are two place that looks very alike but only one place(the latter) should be changed
